### ISSUE TITLE
deprecated macros of console_bridge in rosbag_storage/src/bz2_stream.cpp and lz2_stream.cpp

### ISSUE THREAD

**Issue by majorx234** [ros-gbp/ros_comm-release#1]
console-bridge renamed its logError function to CONSOLE_BRIDGE_logError.
See [commit in cosnole_bridge](https://github.com/ros/console_bridge/pull/48/commitsl) 

suggested solution:
rename these functions and add something like

```
#ifndef CONSOLE_BRIDGE_logError
  #define CONSOLE_BRIDGE_logError logError
#endif
```

to get backward compatiblity with libconsole-bridge-dev < 0.3.0,

**Comment by dirk-thomas** [comment]
This has already been addressed upstream for Kinetic as well as Lunar: ros/ros_comm#1235, ros/ros_comm#1238.
