### ISSUE TITLE
wrong template function call in utilities/message_filters/include/message_filters/subscriber.h

### ISSUE THREAD

**Issue by majorx234** [ros-gbp/ros_comm-release#2]
I've got compiler errors when tryning to compile package  `message filters`.
problem is call of add function in `subscriber.h`

Problem is in function  `cb(..)`
in line 358 there is a call for add funtion with template parameter
`this->add<i>(evt);`
this should be
` this->template add<i>(evt);`

here we need to tell the compiler that we want to call a function template

**Comment by dirk-thomas** [comment]
This repository only contains the release branches. Please report issues in the source repository instead (https://github.com/ros/ros_comm/).

This particular issue seem to have already been reported in ros/ros_comm#1383 as well as been addressed in ros/ros_comm#1388.
